BUILD
Fix relative paths for bazel integration tests.
=> Fix relative paths for bazel integration tests.

.travis.yml
Add .travis.yml configuration.
=> Add .travis.yml configuration.

README.md, tools/BUILD
Add coverage_support filegroup to apple_support.
=> Add coverage_support filegroup to apple_support.

lib/apple_support.bzl, travis_test.sh
buildifier 0.20.0 sets the exist status for lint issues.
=> buildifier 0.20.0 sets the exist status for lint issues.

README.md
Bump the version number in the example.
=> Bump the version number in the example.

BUILD, README.md, WORKSPACE, lib/apple_support.bzl, lib/repositories.bzl, rules/BUILD, rules/apple_genrule.bzl
=> Provide a apple_genrule().

BUILD, lib/BUILD, lib/apple_support.bzl, lib/repositories.bzl, lib/xcode_support.bzl, rules/BUILD, test/BUILD, test/apple_genrule_test.sh, test/apple_support_test.bzl, test/xcode_support_test.bzl, tools/BUILD, travis_test.sh
=> Fix another typo.

CODEOWNERS, lib/apple_support.bzl, lib/xcode_support.bzl, rules/apple_genrule.bzl, test/apple_support_test.bzl
Fix up some markdown in the docstrings.
=> Fix up some markdown in the docstrings.

doc/apple_support.md, doc/rules.md, doc/xcode_support.md, lib/apple_support.bzl, lib/repositories.bzl
=> Docs and skylib usage fixups

lib/framework_migration.bzl
Clean up framework support
This is an NFC, as it supports both the pre- and post- cleanup APIs.
=> Clean up framework support

lib/repositories.bzl
Update Skylib version to 0.8.0
=> Update Skylib version to 0.8.0

doc/apple_support.md, doc/rules.md, doc/xcode_support.md
Add generate markers to the docs.
=> Add generate markers to the docs.

lib/repositories.bzl
.../BUILD: fix build file/module bugs (#18)
=> .../BUILD: fix build file/module bugs (#18)

BUILD, lib/BUILD, rules/BUILD
Add a bzl_library incase something needs it from here.
=> Add a bzl_library incase something needs it from here.

.bazelci/presubmit.yml
Rename the task for the buildkite ui.
Forgot to do this in the previous change adding it.
=> Rename the task for the buildkite ui.

README.md
Bump the version in the example
=> Bump the version in the example

lib/repositories.bzl
=> Bump skylib to 0.9.0

lib/repositories.bzl
=> Update skylib to 1.0.2

doc/apple_support.md
Update the docs.
RELNOTES: None.
=> Update the docs.

.bazelci/presubmit.yml, .bazelci/update_workspace_to_deps_heads.sh
Mostly a revert of commit 9605c3da1c5bcdddc20d1704b52415a6f3a5f422.
=> Enable more CI configs again.

.bazelrc
https://github.com/bazelbuild/bazel/issues/5903
=> Disable incompatible_run_shell_command_string for now

lib/apple_support.bzl
RELNOTES: None
PiperOrigin-RevId: 364797902
(cherry picked from commit d9aee1cfdd4c296d08cab718d5903962119ea34a)
=> Switch to XcodeVersionConfig.execution_info().

test/apple_support_test.bzl
RELNOTES: None
PiperOrigin-RevId: 364986436
(cherry picked from commit feaae213cb6a5af28f83a7ac550d70acc680e5a4)
=> Directly collect the information needed for Apple+Xcode testing.

rules/apple_genrule.bzl
RELNOTES: None
PiperOrigin-RevId: 364986524
(cherry picked from commit 736d2af3e323b8c3d51f2fa53dcbf1be3f331c6c)
=> Skip the indirection and just get the value from the fragment.

lib/apple_support.bzl
These didn't prove to be as generally useful, instead just directly inline the
work (avoiding a lot of extra validation) in run() & run_shell().
Streamline the argument validation now that there are fewer things that need
support.
RELNOTES: Removed action_required_env() and action_required_execution_requirements()
PiperOrigin-RevId: 365832640
(cherry picked from commit f7551fb7a2ded00e7106502d5b1fe9713aa5a0cd)
=> Remove action_required_env() and action_required_execution_requirements()

lib/apple_support.bzl
Directly call `update()` instead of building temporary arrays, doesn't hurt
readability and avoids the indirection/work.
RELNOTES: None
PiperOrigin-RevId: 365833674
(cherry picked from commit 17ecefec71d4e7bebc9134786d05407e595fc4a5)
=> Remove _add_dicts().

rules/apple_genrule.bzl
RELNOTES: None
PiperOrigin-RevId: 365833782
(cherry picked from commit 9382fe9295ebc0696406b53326498f0ae372bcc1)
=> Directly pass the parts needed to apple_support.run_shell.

test/apple_support_test.bzl
RELNOTES: None
PiperOrigin-RevId: 365833288
(cherry picked from commit aa71415a4d277e071e278f2d7edf6b679bbfc60b)
=> Test ctx and explicit args apis.

rules/apple_genrule.bzl
=> Remove unnecessary repo name

rules/private/BUILD
RELNOTES: None
PiperOrigin-RevId: 441866225
(cherry picked from commit 8b0decf90b2be072192b08d87219739e0acbd19a)
=> Update deps and format files.

lib/apple_support.bzl
RELNOTES: None
PiperOrigin-RevId: 445173553
(cherry picked from commit a69fb86b22bed6ab7cc7322b86091ffe17896045)
=> Fail if arg processing requested but no arguments.

MODULE.bazel
=> Bump MODULE.bazel

lib/lipo.bzl
PiperOrigin-RevId: 480139567
(cherry picked from commit dc4deaa83f4b466f56825ba3c2e27704ee6ed221)
=> Add logic to lipo the stub binary to match the requested archs for the Apple build for watchOS extension-dependent applications (watchOS 2 apps).

test/apple_support_test.bzl
RELNOTES: None
PiperOrigin-RevId: 480103119
(cherry picked from commit fb7ab89d22dbe25f5022707db8892eb5bcac2858)
=> Minor style change.

.github/workflows/create-release.yml
I added this before I realized the workflow automatically has this field
=> Remove extra branch configuration

.github/update-module-version.sh, MODULE.bazel
This will make it easier to include toolchains here, similar to the
other repos
=> Use marker for MODULE.bazel grep

crosstool/osx_cc_configure.bzl
This only handles some homebrew case which we do not support
=> Remove unnecessary env replacement

crosstool/cc_toolchain_config.bzl
This reduces the noise a bit with how these are configured
=> Move marker features directly into features list

crosstool/cc_toolchain_config.bzl
This feature did 2 things:
1. It passed `-fobjc-link-runtime` to all C++ actions
2. It passed `-framework UIKit` on non macOS platforms to C++ link
actions
`-fobjc-link-runtime` was also being passed elsewhere to the ObjC link
actions so this flag moved to 1 place in the `default_link_flags` and no
longer needs to be in this feature.
For ObjC link actions we were already passing `-framework UIKit` for
iOS. This makes this feature also apply to C++ link actions.
=> Remove contains_objc_source feature

crosstool/osx_cc_configure.bzl
Using resolve_labels this way didn't work with strict bzlmod
dependencies. We could copy the implementation of that function here,
but for our case it's pretty simple to just do what we need manually.
=> Remove use of resolve_labels

.bazelrc
This is already done in the shell tests but we might as well do it
everywhere
=> Add bazelrc setting up toolchains

test/BUILD, test/main.c, test/main.cc, test/main.m
This makes it easy to test a few different configurations
=> Add some test binary rules

MODULE.bazel
Not sure how it happened, but the buildifier task in #180 is failing due to this.
=> Run buildifier on MODULE.bazel

crosstool/cc_toolchain_config.bzl
https://github.com/bazelbuild/bazel/pull/17355
=> Remove O1 from sanitizer feature flag defaults

crosstool/BUILD.tpl
For https://github.com/bazelbuild/bazel/commit/9f2c62aa489394ae882e07fb97eefb0556075944
=> Add link_extra_lib shim

.bazelci/presubmit.yml
https://github.com/bazelbuild/bazel/issues/17507
=> Downgrade bazel HEAD because of license bug

crosstool/osx_cc_configure.bzl
We require Xcode 13+ (matching the App Store) at this point, so we don't
need to support versions that can't build for Apple Silicon
=> Remove pre Xcode 12 logic

.bazelci/presubmit.yml
Reverts bazelbuild/apple_support#195
=> Revert "Downgrade bazel HEAD because of license bug"

BUILD, configs/BUILD, configs/platforms.bzl, crosstool/BUILD.toolchains, crosstool/BUILD.tpl, platforms/BUILD
This is a common pattern you need to select on. Since we have a limited
set of CPUs it's nice to provide a source of truth for this type of
thing
=> Add config_settings for platforms

test/shell/apple_test.sh, test/starlark_apple_binary.bzl
=> Remove lipobin output

BUILD, configs/platforms.bzl, crosstool/cc_toolchain_config.bzl, platforms/BUILD, test/shell/apple_test.sh, test/transitions.bzl
These are no longer supported with Xcode 14+ which is required for App
Store submissions
=> Remove 32 bit CPUs

test/BUILD, test/cc_test_with_objc_deps.cc, test/objc_lib.h, test/objc_lib.m, test/shell/objc_test.sh, test/underlying_lib.h
This verifies the build and also verifies it actually works which is a
bit nicer
=> Move shell test to cc_test

crosstool/cc_toolchain_config.bzl
In the case someone sets --apple_platform_type to something weird, that
would result in a mismatch of CPU to minimum OS version.
=> Derive platform type from CPU instead of from apple fragments

crosstool/cc_toolchain_config.bzl
Suppresses linker warnings like these, which are new with Xcode 15:
```
ld: warning: ignoring duplicate libraries: '-lm', '-lpthread', '-lz'
```
Relevant Slack conversations:
- https://bazelbuild.slack.com/archives/C04DFUBQGSU/p1695063579429469
- https://bazelbuild.slack.com/archives/CD3QY5C2X/p1695063506152109
- https://bazelbuild.slack.com/archives/C04DFUBQGSU/p1689257981712829
=> Use `no_warn_duplicate_libraries` by default

constraints/BUILD
Needed to fix toolchain resolution.
=> Add `default_constraint_value` to `target_vendor` constraint

.bazelrc
https://github.com/bazelbuild/rules_swift/issues/1083
=> Disable treat_warnings_as_errors for now

.bazelci/presubmit.yml
- Remove 6.x issues
- Remove split bzlmod job, assume bzlmod only for 7.x
=> Cleanup CI config

crosstool/BUILD.tpl, crosstool/cc_toolchain_config.bzl
Fixes https://github.com/bazelbuild/apple_support/issues/298
Much of this logic was loosely copied from https://github.com/bazelbuild/bazel/blob/84dd8c129ba4b24a58f0159adc9c93286a02176f/src/main/starlark/builtins_bzl/common/objc/objc_common.bzl
=> Remove apple_cc_toolchain use

crosstool/cc_toolchain_config.bzl
Mirrors this upstream feature https://github.com/bazelbuild/bazel/issues/12009
=> Add external_include_paths feature

test/available_xcodes_test.bzl, test/shell/BUILD, test/xcode_config_test.bzl, test/xcode_support_test.bzl, test/xcode_version_test.bzl
Needed to cherry-pick d5a60a61d05cb1bfaaf690a5bec532f278421202.
=> Fix labels for Bazel HEAD

crosstool/cc_toolchain_config.bzl, test/linking_tests.bzl, test/test_data/BUILD
=> Remove `apply_implied_frameworks` feature from `implies` action configs

CODEOWNERS
see also:
bazelbuild/rules_swift#1455
bazelbuild/rules_apple#2602
=> Add Aaron to `CODEOWNERS`

.bcr/presubmit.yml
Needed to use dev dependencies in BCR presubmit.
https://buildkite.com/bazel/bcr-presubmit/builds/10562
=> Use a BCR test module for tests

crosstool/cc_toolchain_config.bzl
https://github.com/bazelbuild/bazel/pull/25682
=> Support eventual removal of do_not_use_macos_set_install_name

.bazelci/presubmit.yml
This way changes between 7.0 and 7.x cause CI failures
=> Test against 7.0 explicitly

crosstool/osx_cc_wrapper.sh.tpl
Fixes https://github.com/bazelbuild/apple_support/issues/399
=> Use absolute path to dirname

xcode/BUILD, xcode/private/BUILD, xcode/private/providers.bzl, xcode/xcode_config.bzl, xcode/xcode_version.bzl
Upstreams:
- https://github.com/bazelbuild/apple_support/commit/ed485101a5875ae5e1db1fb5f6d21a8c8c65f1e2
- https://github.com/bazelbuild/apple_support/commit/740030875b2758d46d0447fea0b43254090af24d
=> Upstream: add `sdk` attribute to `xcode_version`

lib/BUILD, lib/xcode_support.bzl, xcode/BUILD, xcode/private/BUILD, xcode/private/providers.bzl, xcode/xcode_config.bzl, xcode/xcode_version.bzl
Upstreams:
- https://github.com/bazelbuild/apple_support/commit/c745861a9cc17032750693dee082201219b15880
=> Upstream: Define `xcode_support.get_current_sdk` and `xcode_support.get_current_xcode` helpers

test/shell/testenv.sh, test/transitions.bzl
This was removed from bazel @ HEAD
=> Remove apple_crosstool_top

.bcr/presubmit.yml
I've been manually patching these in the last few releases
=> Update BCR CI to exclude some more tests

crosstool/cc_toolchain_config.bzl, crosstool/wrapped_clang.cc, test/shell/wrapped_clang_test.sh
I don't think this is needed anymore
=> Remove absolute AST path functionality
