lib/xcode_support.bzl
Add blank line before Returns block.
The new buildifier --lint things "Returns" is an argument to the function
unless there is a blank line before it.
=> Add blank line before Returns block.

.bazelci/presubmit.yml, .travis.yml, README.md, travis_test.sh
Simplify the running of buildifier on CI.
As of 0.22.0 there are enough improvements in outputs and exit codes that
it seems to make more sense to no longer try to pretty the results and
just rely on a run and exit status to add a footer telling folks how
to fix up things if something is found.
=> Simplify the running of buildifier on CI.

.bazelci/presubmit.yml, .travis.yml, travis_install.sh, travis_test.sh
Travis CI Cleanup.
Bazel's BuildKite seems to be fine for the bazel builds, so remove the support
for doing bazel builds on Travis.
Note: Keeping the matrix as a manual build and some of the conditions in the
scripts just to reduce the chances of something not being right, as eventually
the BuildKite setup will match the buildifier support and these files will
just get dropped.
=> Travis CI Cleanup.

CONTRIBUTING.md
Update contributing information.
Since this isn't part of bazel's core projects, directly provide more info
instead of linking to docs they have been evolving as they work on their
processes.
=> Update contributing information.

README.md
Show the build status only for the master branch.
Otherwise a test_* branch that doesn't currently pass turns the badge red
because it was the "most recent" build on buildkite.
=> Show the build status only for the master branch.

.bazelci/presubmit.yml, .bazelci/update_workspace_to_deps_heads.sh
Add config to test some deps at their heads.
Add a helper script and new ci config to run the script modifying the
WORKSPACE to get head versions of some dependencies to help catch if
they were to land something that would break the build.
=> Add config to test some deps at their heads.

rules/apple_genrule.bzl
Use a list comp to build the depset to avoid overly nesting.
=> Use a list comp to build the depset to avoid overly nesting.

lib/BUILD
Add missing BUILD dep introduced by https://github.com/bazelbuild/apple_support/commit/e5588297491dfb4c546fbe13571a94e1e8a0929a.
=> Add missing BUILD dep introduced by https://github.com/bazelbuild/apple_support/commit/e5588297491dfb4c546fbe13571a94e1e8a0929a.

lib/apple_support.bzl, rules/apple_genrule.bzl, test/apple_support_test.bzl
Set execution requirements for Starlark rules that use apple_support based on the availability of the selected Xcode.
This is part of a series of changes that set the execution requirements for actions generated by rules that require Xcodes. The dynamic scheduler will later be modified to run those actions locally/remotely accordingly, but this does not currently change behavior.
RELNOTES: None.
=> Set execution requirements for Starlark rules that use apple_support based on the availability of the selected Xcode.

doc/apple_support.md, lib/apple_support.bzl
Migrated app_assets_validation partial and bitcode_symbols partial to use that new macro instead of ctx, passing the rest of the inputs through as arguments that were previously obtained through directly accessing ctx.
PiperOrigin-RevId: 330988093
=> Created a macro to replace the wrapper macros used to determine platform features from ctx in the Apple BUILD Rules today.

doc/apple_support.md, lib/apple_support.bzl
=> Changes to apple_support to allow for using the run and run_shell macros without a ctx argument.

.bazelrc, lib/apple_support.bzl, rules/apple_genrule.bzl, test/apple_support_test.bzl
This is required for this migration https://github.com/bazelbuild/bazel/issues/5903
=> Remove passing lists of args to genrule

constraints/BUILD
PiperOrigin-RevId: 355196884
(cherry picked from commit 5117edbfd73838c3e64366ff28b5cc4ec3ef33fe)
=> Move target_environment to apple_support so it can be relied upon by rules_swift and rules_apple.

constraints/BUILD
This aligns with the LLVM triple representing this platform as a variant of iOS.
PiperOrigin-RevId: 358194575
(cherry picked from commit 84ad2df29043b0c8f7eef150dd73f30d2e5216d0)
=> Add the Catalyst constraint to the list of target environments.

BUILD
RELNOTES: None
PiperOrigin-RevId: 365821014
(cherry picked from commit 800b7748496bfc50ebb542327bb3ce9cc0d9f531)
=> Remove the alias.

lib/apple_support.bzl, test/apple_support_test.bzl
RELNOTES: apple_support.path_placeholders.platform_frameworks() no longer accepts a ctx argument.
PiperOrigin-RevId: 364873873
(cherry picked from commit 9c175c7f47c476006491be5dce510a15f05067df)
=> Remove ctx support from path_placeholders.platform_frameworks().

rules/BUILD, rules/apple_genrule.bzl
- outputs isn't a depset, always a list, so don't make a depset to have to call to_list()
- inputs can be a depset, so don't flatten
- Remove the use of skylib's paths, and just fetch dirname from the File
RELNOTES: None
PiperOrigin-RevId: 366162426
(cherry picked from commit ec1cd1ffa5a91e6f57b92ee4f7a6de26717f1b22)
=> Remove some of the extra depset work.

BUILD, lib/BUILD, lib/lipo.bzl
Currently, this only supports `create`, but could support other `lipo` actions in the future.
PiperOrigin-RevId: 373572887
(cherry picked from commit d381321b41bcfc1a7b657c7f3c2ba66b9cea4e40)
=> Add a module with methods to create actions that invoke `lipo`.

lib/macos_universal_binary.bzl, lib/transitions.bzl, lib/universal_binary.bzl, test/BUILD, test/test_data/BUILD, test/test_data/main.cc, test/universal_binary_test.bzl
This is basically a copy of the new `apple_universal_binary` rule but
with a simpler interface (there are no `minimum_os_version` and
`platform_type` attributes), and the output binary is forced to be
multi-arch. This rule is meant to be used for host/exec tools so that
they are built as universal binaries regardless the architecture of the
execution platform.
=> Add `universal_binary` rule to build multi-arch macOS binaries

rules/apple_genrule.bzl, test/BUILD
[`ctx.resolve_command()`](https://docs.bazel.build/versions/main/skylark/lib/ctx.html#resolve_command) seems to return a list of arguments like `["/bin/bash", "-c", "mycommand"]`. These were being simply joined with a single whitespace and passed into `run_shell()`, effectively concatenated into `/bin/bash -c mycommand`. This works fine if the command doesn't have any arguments but fails if it does:
```
INFO: Analyzed 21 targets (0 packages loaded, 0 targets configured).
INFO: Found 17 targets and 4 test targets...
ERROR: /code/apple_support/test/BUILD:34:14: Executing apple_genrule //test:touched failed: (Exit 1): bash failed: error executing command /bin/bash -c '/bin/bash -c touch bazel-out/darwin-fastbuild/bin/test/genrule_touched.txt'
Use --sandbox_debug to see verbose messages from …
```
=> Fix apple_genrule

lib/apple_support.bzl
The binary is a `sh_binary`, so it likely doesn't matter, but should be more correct.
b/204580651 will likely result in more follow up here (atleast with guidance for the things that use this apis that need these).
PiperOrigin-RevId: 406829632
(cherry picked from commit fd0e5ba0b07e30ac3a12c86bda5b2c8431db6d88)
=> Change `cfg` to `"exec"` for xcode_path_wrapper.

rules/universal_binary.bzl, test/test_data/BUILD
The `lib` directory is for Starlark modules.
=> Move `universal_binary.bzl` to the `rules` directory

platforms/BUILD
These platforms can be used in the case you want to use bazel platforms
support. If you need more customization for remote execution you can use
these as the parent platforms for your custom ones.
=> Add all standard platforms

lib/BUILD, lib/lipo.bzl
PiperOrigin-RevId: 463400246
(cherry picked from commit 6ed0d77fc4ee23b317846888e399e299acaadec8)
=> Explicitly create the containing directory to avoid an occassional error from lipo; "can't create temporary output file [...] (Permission denied)".

lib/apple_support.bzl
This is useful for passing in native binaries (e.g. java_binary).
PiperOrigin-RevId: 473255419
(cherry picked from commit 6022b1bc7d0e0928e0c9baad809df196a9b22075)
Fixes https://github.com/bazelbuild/apple_support/issues/131
=> Allow FilesToRunProvider type executable in apple_support.run.

MODULE.bazel
This was [recently added to Bazel](https://github.com/bazelbuild/bazel/commit/73ed74ec5da1e787e2bffb19ebca6c94c437aa38) and will help in keeping the repository name the same during the migration period. 
We will need to remember to add this attribute to the `MODULE.bazel` checked-in into the `bazel-central-registry` once we cut a new release.
=> Add repo_name to module definition

lib/BUILD
This target isn't compatible with any other platform other than macOS so we're now declaring its compatibility. This was discovered during the bzlmod integration: https://github.com/bazelbuild/bazel-central-registry/pull/196
=> Skip `swizzle_absolute_xcttestsourcelocation` on non-macOS platforms

lib/BUILD
This reverts commit a7ef1baaff1e001e3c713d73d3ccfcfeaef7f967.
=> Revert "Skip `swizzle_absolute_xcttestsourcelocation` on non-macOS platforms (#137)"

.github/workflows/create-release.yml
Pushing didn't work because of branch protections. This requires someone
to +1 but should work. The archive will still contain the updated
version even though that mismatches the sha of the tag, which is a bit
weird.
=> Use a PR instead of pushing MODULE.bazel bump

.github/workflows/create-release.yml
The bot token doesn't have access to do this. Not a huge deal for us to
enable / manually merge.
=> Remove automerge from create-release

crosstool/BUILD.tpl
This workaround is only for the case where xcode_locator fails. We do
not allow that to fail and do not fall back if it does
=> Remove cc-compiler-darwin

crosstool/BUILD.toolchains, crosstool/BUILD.tpl, crosstool/osx_cc_configure.bzl
This was added because the NDK requires all toolchains have this in
bazel itself. Since this toolchain isn't part of bazel we no longer need
this.
=> Remove armeabi toolchain

crosstool/setup.bzl
Most of these variables were windows or unix specific. This leaves just
the ones we actually use with comments on their purpose
=> Update allowed env vars

crosstool/cc_toolchain_config.bzl
This was added to the upstream unix toolchain, but never the apple one
=> Add treat_warnings_as_errors feature

crosstool/cc_toolchain_config.bzl, crosstool/wrapped_clang.cc, test/shell/wrapped_clang_test.sh
This allows more generic flags to be passed that need to use the
execroot. This makes it easier for users to pass things like this
without requiring crosstool modifications
=> Add __BAZEL_EXECUTION_ROOT__ command line replacement

crosstool/cc_toolchain_config.bzl
`all_link_actions` is actually misleading as it doesn't include
Objective-C links or static links, this replaces this common use case
with a new variable. More work needs to be done to remove
`all_link_actions`
=> Add new _DYNAMIC_LINK_ACTIONS variable

crosstool/cc_toolchain_config.bzl
Not sure if this should ever differ, but for now this makes it more
clear that this variable isn't actually used
=> Hardcode host_system_name

crosstool/cc_toolchain_config.bzl
If you ever hit this it's always a misconfiguration somewhere.
Realistically you only hit it if you're editing the rules but sometimes
if you don't stop immediately the rest of the output can be very noisy
and misleading.
=> Add error for -Wincompatible-sysroot

crosstool/libtool.sh, crosstool/libtool_check_unique.cc
This is useful for debugging. Without it being in these lists the static archive fails
https://github.com/bazelbuild/bazel/pull/16367
=> Allow -v to libtool

crosstool/cc_toolchain_config.bzl
https://github.com/bazelbuild/bazel/commit/25be21130ba774e9f02cc39a010aafe64a3ab245
=> Make objc++-executable and objc-executable actions behave the same

crosstool/cc_toolchain_config.bzl
This removes absolute paths from code coverage data. This is also
supported in swift with `swift.coverage_prefix_map`
=> Add coverage_prefix_map feature

.bcr/presubmit.yml
These tests currently fail because of runfiles issues. Really we don't
care that the BCR tests much anyways, just that the file loads work at
all. Our CI covers the rest.
https://bazelbuild.slack.com/archives/C014RARENH0/p1676506451712139
=> Exclude some tests from bcr

crosstool/cc_toolchain_config.bzl
This was removed from bazel in https://github.com/bazelbuild/bazel/commit/004c73c4e5735dcea238e24a0e4e2acdf9eb28f0 but is still required to support bazel <7.x.
=> Remove ObjC++ executable constant

crosstool/cc_toolchain_config.bzl
This was removed from bazel in the 7.x releases, but we still want to
support for now. This makes it more clear what we need to remove when we
drop the older versions.
https://github.com/bazelbuild/bazel/commit/e1cb203f6eeb376a5b8495de27272d4c952f9e19
=> Extract objc-archive name

crosstool/osx_cc_configure.bzl
This switches all macOS toolchain setup compiles and executes to use the
default timeout of 600s. This should help avoid issues on GitHub actions
where these timeout and cause build failures. The common case shouldn't
really be affected.
https://github.com/bazelbuild/bazel/issues/17437
=> Increase timeouts for macOS toolchain setup

crosstool/cc_toolchain_config.bzl
This flips the defaults of 3 features:
- relative_ast_path: this makes sure that the swift AST entries embedded
in the final binaries uses relative paths for hermeticity. This could
potentially break debugging for users relying on absolute paths, in
which case they should use `platform settings -w "$PWD"` to change the
lldb PWD so the relative paths are valid, or they should disable this
feature.
- oso_prefix_is_pwd: this is similar to above except its for N_OSO
entries in the final binary. The same workarounds apply
- remap_xcode_path: this removes absolute paths to Xcode from the
binary. This shouldn't affect debugging because lldb's defaults should
fall back to the same paths even if they aren't in the debug info
=> Flip defaults of hermetic debug info flags

crosstool/osx_cc_configure.bzl, crosstool/setup.bzl
In the case xcode-locator fails to compile, the only error was the one
assuming you have no Xcode versions available
=> Propagate xcode-locator error to fail()

README.md, crosstool/osx_cc_configure.bzl
Since this toolchain requires Xcode, running xcode_locator during
toolchain setup is likely duplicative. The only things it's used
for is to check that they exist, and to add to the allowed include
directories. The include directories already includes /Applications
which is where most people likely have Xcode installed, so as long
as that can be relied on, fetching these values isn't necessary. This
saves a few seconds when the toolchain is reconfigured.
bazelbuild.slack.com/archives/CD3QY5C2X/p1652819625121889
=> Add BAZEL_ALLOW_NON_APPLICATIONS_XCODE to run xcode-locator

crosstool/cc_toolchain_config.bzl, test/BUILD, test/linking_tests.bzl, test/rules/action_command_line_test.bzl, test/test_data/BUILD
This extracts the -ObjC flag into a separate crosstool feature, and
makes it apply to all CC linking actions. Previously this only applied
to objc-executable actions, but as this gets unified into the cc linking
behavior it makes sense to apply it to the cc actions as well. This has
the potential downside that if you had a cc_binary target that had
Objective-C in the dependency tree that it did not use, previously it
would not have been loaded and now it would. If that becomes a problem
this flag can be removed on thew binary in question by disabling this
feature. This also allows us to remove this flag from rules_swift's
logic since it was there for the same reason.
=> Move -ObjC into a separate feature

crosstool/cc_toolchain_config.bzl, test/linking_tests.bzl
Since we went a different route in rules_swift and require the -ObjC
flag to be disabled there too, this isn't as necessary. This reduces the
risk of people making new reliance on -ObjC and when other changes land
to flip the default on this we won't have to worry about that case.
=> Remove -ObjC from C++ links

constraints/BUILD
This allows the registered macOS toolchains to match Bazel's auto- generated host platform for macOS.
=> Make `device` the default of `target_environment`

crosstool/cc_toolchain_config.bzl
Now that Xcode 14.1 is the minimum supported to the App Store, and Xcode
14.0 dropped support for bitcode, we don't need to handle these flags
anymore.
=> Remove support for bitcode

crosstool/cc_toolchain_config.bzl
Mirroring https://github.com/bazelbuild/bazel/pull/18280 so it's easier
to swap between the toolchains
=> Update C++ standard default to 14

crosstool/setup.bzl
This can be used to invalidate the toolchain when your Xcode version
changes but the path to Xcode doesn't. This is required if you want to
avoid non-hermetic issues when switching Xcode versions. Previously we
used USE_CLANG_CL for this since it was otherwise ignored, but we should
move to this one which makes it more clear what the purpose is.
=> Add new XCODE_VERSION toolchain env var

configs/BUILD
As of bazel 7.x 'darwin' as a CPU is no longer valid, and
'darwin_x86_64' is used instead. But while users of this config setting
might still be on older versions of bazel this adds support for that in
the config settings.
=> Fix apple config setting group for 'darwin' CPU

crosstool/cc_toolchain_config.bzl
This makes it easier to understand this variable is different from
`$DEVELOPER_DIR` and also makes it "absolute" so that tools like
index-import don't try to absolutize it.
=> Replace DEVELOPER_DIR remapping with '/PLACEHOLDER_DEVELOPER_DIR'

test/BUILD, test/binary_tests.bzl, test/rules/apple_verification_test.bzl, test/shell/BUILD, test/shell/verify_binary.sh, test/test_data/BUILD
This is a useful test rule copied from rules_apple stripped down to only
what we need right now. This will allow us to remove some of our shell
tests, and write starlark tests instead of shell tests in the future.
=> Add stripped down apple_verification_test

crosstool/cc_toolchain_config.bzl
We get `-lc++` from the `link_libc++` feature which is enabled for all
linking actions. We get `-target` from `default_link_flags` which is
enabled for all linking actions. This fixes ld-prime's new warning for
`cc_binary` targets and anything using `cc_common.link` (`swift_binary`).
=> Remove cpp_linker_flags feature

test/shell/BUILD, test/shell/apple_test.sh, test/shell/integration_test_setup.sh, test/starlark_apple_static_library.bzl
No reason to complicate the shell tests with generating this test rule
=> Move starlark_apple_static_library into bzl file

BUILD, test/BUILD, test/shell/BUILD
If the test/ package is invalid we still shouldn't fail rules_apple.
This can happen when bazel deletes an API that we use only in tests in
this repo
=> Remove //test:for_bazel_test from global for_bazel_tests

lib/repositories.bzl
If nothing loads this then it comes from bazel itself so the version
depends on your version of bazel, we want a newer one to support
visionOS.
=> Add platforms to default repositories.bzl

.bazelci/presubmit.yml, test/BUILD, test/shell/apple_test.sh, test/shell/objc_test.sh, test/starlark_apple_binary.bzl, test/starlark_apple_static_library.bzl, test/test_data/BUILD, test/transitions.bzl
This was removed upstream but we still need the smallest possible
transition for testing, this copies the one from rules_apple and removes
a bunch of the features. If this ends up being too much of a pain to
update we'll have to find a different solution.
=> Remove apple_common transitions

README.md, configs/platforms.bzl, crosstool/cc_toolchain_config.bzl, lib/BUILD, test/binary_tests.bzl, test/linking_tests.bzl, test/rules/apple_verification_test.bzl, test/shell/verify_binary.sh, test/test_data/BUILD, test/test_data/lib.cc, test/test_data/lib.m, test/test_data/main.m, test/transitions.bzl
Depends on https://github.com/bazelbuild/bazel/pull/18905 and https://github.com/bazelbuild/platforms/pull/71
=> Add initial visionOS support

.bazelrc
Just helps make sure we don't introduce any weird platform mismatch that
ld doesn't fail on
=> Add warnings as errors for tests

configs/platforms.bzl
This fixes so that rules_apple work with C++ toolchain resolution enabled.
Failure example: https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/1638#018a6805-45af-4dcc-a83b-3f3f3231713c
Tested manually.
=> Fix ios_arm64e cpu value to match platforms cpu constraint

lib/transitions.bzl
Fixes: https://github.com/bazelbuild/rules_swift/issues/1103
=> Add platforms to apple_universal_binary transition

lib/transitions.bzl
This way on Linux in the default case we forward the platforms
=> Add platforms as input to universal transition

lib/apple_support.bzl
Now that bazel 7.x has
https://bazel.build/reference/command-line-reference#flag--incompatible_merge_fixed_and_default_shell_env
enabled by default, we can set `use_default_shell_env = True` moving
forward. This makes actions respect `--action_env=FOO` which can be
useful for things like `TOOLCHAINS`, `ZERO_AR_DATE`, `TMPDIR`, etc.
Previously these were ignored.
=> Enable use_default_shell_env everywhere

configs/platforms.bzl, lib/transitions.bzl, platforms/BUILD, test/transitions.bzl
This allows people to use custom versions of the platforms, including child platforms of the default ones, which allows for custom additional constraints and platform properties.
=> Add build flags to allow overriding platforms used in transitions

.bazelci/presubmit.yml, .bazelrc, lib/transitions.bzl
You can build univeral_binary targets on Linux and they just
passthrough. This validates we don't break that.
=> Add very basic linux CI

README.md
https://github.com/bazelbuild/rules_cc/pull/199
=> Update toolchain setup docs

lib/apple_support.bzl
PiperOrigin-RevId: 568908396
(cherry picked from commit 4d4c409e744f1eb061bd0a93add789913430a9d2)
=> Move methods to report platform constraints as strings to apple_support.

configs/BUILD
Needed to bring rules_apple `bzl_library` dependencies up-to-date.
=> Add `//config:platforms` `bzl_library`

.gitignore
This file is generated by default by bazel @ HEAD but we don't really
want to manage it. This way it can be generated locally and folks can
build offline if they have generated it at least once.
=> Ignore MODULE.bazel.lock (#1130)

crosstool/cc_toolchain_config.bzl
In rules_apple we've started using cc_common.link in 1 place, which
doesn't set this variable in bazel since this is an Apple specific
feature in bazel. This means if you try to link a intents stub binary
and pass `--objc_generate_linkmap` the link will fail. We don't care
about generating linkmaps for that binary anyways since it's just an
intermediate artifact, so this fixes that link. This has the downside
that this could hide issues and silently not create linkmaps for links
that should support them in the future.
=> Only enable linkmap if the variable exists

README.md
The big change here is that bazel 7.x shipped with toolchain resolution
flipped, so that no longer requires any configuration.
=> Update toolchain setup instructions

crosstool/cc_toolchain_config.bzl
Mirrors https://github.com/bazelbuild/bazel/pull/20847
This variable isn't supported until the linked change, but if anyone
hit this codepath today it wouldn't work either so it's safe to use
since it just changes the error message to something else.
=> Replace -l: with path to library

configs/platforms.bzl, crosstool/cc_toolchain_config.bzl, test/binary_tests.bzl, test/transitions.bzl
Since Apple released this without intel support, I think it's a good
time to remove it
=> Remove visionos_x86_64 support

.bcr/presubmit.yml
There is a new requirement to include bazel version. Also the machines
there don't have the visionOS SDK yet
=> Update bcr CI config

test/starlark_apple_binary.bzl
After moving linking behavior to starlark this is required even though
we don't care about it. It's just for tests in this case.
=> Fix bazel HEAD compatibility

crosstool/cc_toolchain_config.bzl, test/linking_tests.bzl
This change makes `-dead_strip` always be enabled for `opt` builds,
regardless of `--objc_enable_binary_stripping`. This should be the right
default for everyone, if not we can look at adding a way to disable it.
This also allows passing `--features=dead_strip` to enable `-dead_strip`
in other configurations, which previously wasn't supported if you
weren't using `opt`.
=> Enable -dead_strip by default for opt builds

.bcr/presubmit.yml
During queue times it can get annoying. Having macOS and any Linux
should be good enough for this repo, we're just validating that things
work at all with these.
=> Reduce number of BCR CI jobs

.bcr/presubmit.yml
Something about --incompatible_enable_cc_toolchain_resolution with 6.x
makes it so we can't run all our tests on the bcr presubmit. This splits
6.x out so we can run them all for newer bazel versions.
=> Update bcr presubmit for more tests on 7.x+

lib/apple_support.bzl
Use a hash of the first output rather than the full path so it is
less likely to hit path limits when the target where the helper is
used is also deep in a directory structure.
PiperOrigin-RevId: 608607365
(cherry picked from commit 832646cefde1d9166389ccec1ea02af126fc687e)
=> Shorten the path used for the processor script.

crosstool/setup.bzl
This is the same as BAZEL_NO_APPLE_CPP_TOOLCHAIN but this is the bazel
6.x naming. I don't remember why we didn't support this but this should
easy the upgrade for people using this old var who are also pulling in
apple_support for some reason and cannot easily remove it.
=> Add support for BAZEL_USE_CPP_ONLY_TOOLCHAIN

crosstool/cc_toolchain_config.bzl
Mirrors https://github.com/bazelbuild/bazel/commit/bd2da6e977172398bb6612c3a45e91fd1192961a.
=> Add `gcc_quoting_for_param_files` feature

MODULE.bazel, lib/repositories.bzl
Fixes a Bazel @ HEAD issue in `rules_swift`
```
ERROR: Error computing the main repository mapping: Label '@@platforms//host:extension.bzl' is invalid because 'host' is not a package; perhaps you meant to put the colon here: '@@platforms//:host/extension.bzl'
```
=> Update platforms to 0.0.9

crosstool/cc_toolchain_config.bzl
This reverts commit 4df4418dd01229e596aa7b63a6d1594f56ed5613.
Until `dsym_path` is no longer incorrectly quoted by Bazel, or we have a workaround in place.
=> Revert "Add `gcc_quoting_for_param_files` feature (#314)"

BUILD, xcode/BUILD, xcode/available_xcodes.bzl, xcode/xcode_config.bzl, xcode/xcode_config_alias.bzl, xcode/xcode_version.bzl
This change only stubs out rules; providers and flags will come later. The providers in particular need some more thought before locking down their names, since the current names (like `apple_common.XcodeVersionConfig`) don't meet Starlark provider naming conventions.
PiperOrigin-RevId: 612472977
(cherry picked from commit 217743145706a70a516987279a8027819ae892cb)
=> Add stubs for the Xcode rules in apple_support, for eventual migration from Bazel.

xcode/BUILD, xcode/providers.bzl
This currently just re-exports the native definition of the provider (with the name slightly changed to meet Starlark's requirements). When it is migrated out of Bazel, it will be redefined here in Starlark.
PiperOrigin-RevId: 625057283
(cherry picked from commit f8d0988a2693d2741a5fc785ef0e3aa0999afd76)
=> Add `apple_support/xcode/providers.bzl` to export `XcodeVersionInfo`.

.bazelci/presubmit.yml, test/BUILD, test/available_xcodes_test.bzl, test/test_helpers.bzl, test/xcode_config_test.bzl, test/xcode_version_test.bzl
This moves tests from `XcodeVersionTest.java` and part of `XcodeConfigTest.java`. The latter is so large that I'm breaking it up into multiple changes to keep the individual ones smaller. It also stubs out the tests from `AvailableXcodesTest.java`, but the provider they use is restricted to built-in Starlark, so we can't actually migrate those yet.
Since the rules in `apple_support` are still just forwarding to the native rules, these tests will be verifying their behavior. This is what we want, because when we migrate the rule implementations themselves over to `apple_support`, we can verify that we did it correctly via these tests.
Unfortunately, some tests can't be migrated, because Starlark tests don't let you set `--experimental_*` flags in config transitions. If those flags are …
=> Migrate the first batch of Xcode rules' unit tests from Java to Starlark.

MODULE.bazel, WORKSPACE, crosstool/cc_toolchain_config.bzl, lib/repositories.bzl
This reverts commit cf271a330b08a3bbd8ad61241d03787683d5a1c5.
This adds a dependency on **bazel_features** in order to know when it's safe to enable `gcc_quoting_for_param_files` by default.
=> Reapply "Add `gcc_quoting_for_param_files` feature (#314)"

.bazelci/presubmit.yml, crosstool/BUILD.tpl, crosstool/cc_toolchain_config.bzl, crosstool/generate-modulemap.sh, crosstool/osx_cc_configure.bzl, crosstool/setup.bzl, crosstool/wrapped_clang.cc, test/layering_check/BUILD, test/layering_check/a.h, test/layering_check/b.h, test/layering_check/c.cpp, test/layering_check/c.m, test/shell/layering_check_test.sh
This feature currently applies to C/C++ compiles. It validates that for
every header you import you have a corresponding target in your deps
that surfaces that header. Bazel handles a lot of this logic internally
in the CC rules but it's up to us to provide a system-level modulemap
file that contains all system headers, so that non-system headers that
aren't in your deps are correctly flagged as a layering check violation.
To do this we use find to discover all headers in the current
DEVELOPER_DIR. There are a few potential caching issues surfaced with
this:
1. If the paths were absolute, the Xcode path would be an input. We
avoid this by storing relative paths, and then using a vfsoverlay to
make it "look" like the modulemap is inside of Xcode itself, which is
the only way to make …
=> Add support for layering_check

test/BUILD, test/test_helpers.bzl, test/xcode_config_test.bzl
PiperOrigin-RevId: 630133992
(cherry picked from commit d5a60a61d05cb1bfaaf690a5bec532f278421202)
=> Migrate the rest of the Xcode tests from Bazel core (Java) to Starlark (except those that can't be migrated because they use experimental flags)

.bazelci/presubmit.yml, crosstool/BUILD.tpl, crosstool/cc_toolchain_config.bzl, crosstool/wrapped_clang.cc, test/header_parsing/BUILD, test/header_parsing/invalid_header.h, test/header_parsing/valid_header.h, test/shell/header_parsing_test.sh
This feature enables bazel to validate "C++" header files through clang.
Without this you only get this type of validating when you actually
include the library elsewhere.
Similar to layering_check we have to validate this outside of normal
bazel because we are expecting build failures and need to parse the logs
This mirrors https://github.com/bazelbuild/bazel/pull/21560
=> Add support for parse_headers

crosstool/cc_toolchain_config.bzl
This resolves an issue where build would fail if number of arguments sent to the `libtool` would exceed limit set by the OS kernel. A common error would look like this:
```
INFO: Analyzed target //app:app (132 packages loaded, 13220 targets configured).
ERROR: /Users/adincebic/developer/bazel-ios-swiftui-template/app/BUILD.bazel:16:14: Compiling Swift module //app:app.library failed: (Exit 7): worker failed: error executing SwiftCompile command (from target //app:app.library) bazel-out/darwin_arm64-opt-exec-ST-d57f47055a04/bin/external/rules_swift~/tools/worker/worker swiftc ... (remaining 1 argument skipped)
Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
error: forking process failed …
```
=> Enable archive_param_file by default

.bcr/presubmit.yml
This still generally works, but constantly updating this list of targets
is annoying. I don't think it's worth doing just to keep BCR CI, we
still test 6.x on our own CI
=> Remove 6.x bzlmod CI

crosstool/cc_toolchain_config.bzl, test/compiling_tests.bzl
maintains the default behavior of passing `-DNS_BLOCK_ASSERTIONS=1` for opt builds. for builds where this is undesirable, set `--features=-ns_block_assertions` to unconditionally not-set this flag, without having to unset the entire `default_compile_flags` feature.
does not add tests, but i can add them if requested.
=> support selectively disabling NS_BLOCK_ASSERTIONS for opt builds

crosstool/cc_toolchain_config.bzl
This supports `,` in `runtime_solib_name`.
=> Use `-Xlinker` for `-install_name`

lib/apple_support.bzl, test/apple_support_test.bzl
PiperOrigin-RevId: 676001180
Cherry picks: https://github.com/bazelbuild/apple_support/commit/dc76a5feac40c48180badb45ce0efe8a69a8ebcb
=> Remove `ctx` parameter from `apple_support.{run,run_shell}`

crosstool/cc_toolchain_config.bzl
These 2 were replaced by the 1 above 8 years ago, copy pasta
=> Remove unused crosstool flags

crosstool/BUILD.tpl
This didn't vary per platform so we don't need N of them
=> Remove extra unnecessary filegroups

crosstool/cc_toolchain_config.bzl, crosstool/wrapped_clang.cc, test/binary_tests.bzl, test/shell/BUILD, test/shell/verify_relative_oso.sh, test/test_data/BUILD
When bazel executions actions in the sandbox, pwd is a path like this:
```
/private/var/tmp/_bazel_ksmiley/92410d0e3373f265902564b48493ac12/sandbox/darwin-sandbox/8/execroot/_main
```
Inside this directory are the inputs, which are symlinks to outside of
this pwd:
```
/private/var/tmp/_bazel_ksmiley/92410d0e3373f265902564b48493ac12/sandbox/darwin-sandbox/1/execroot/_main/bazel-out/darwin_arm64-dbg/bin/_objs/main/main.o -> /private/var/tmp/_bazel_ksmiley/92410d0e3373f265902564b48493ac12/execroot/_main/bazel-out/darwin_arm64-dbg/bin/_objs/main/main.o
```
ld64 resolves the absolute path to this object file, including resolving
symlinks, _before_ it strips the -oso_prefix argument. Because of this
the previous `__BAZEL_EXECUTION_ROOT__` replacement, which was the
sandbox pwd, isn't actually a …
=> Fix oso_prefix paths

crosstool/cc_toolchain_config.bzl, test/linking_tests.bzl
`ld` starting Xcode 15 (`ld_prime`) now supports this option to perform more general code de-deduplication passes which it was not doing prior.
It is not documented anywhere but Xcode 15+ has this enabled by default in the default Release scheme (which has`Optimization Level = Fastest/Smallest -Os` by default).
I'm adding this as a separate feature so that it can be disabled but there could be an argument whether to enable this by default !
Fun note: passing any character after `-O` performs the same as `-Os`...
=> Enable link time -Os in opt builds

crosstool/osx_cc_configure.bzl, crosstool/setup.bzl
There is a bug in Bazel where the repository symlinks can resolve (nondeterministically in a race condition way) to old contents of files. This leads to errors like:
```
ERROR: error loading package '@@apple_support~~apple_cc_configure_extension~local_config_apple_cc//': Encountered error while reading extension file 'cc_toolchain_config.bzl': Unexpected short read from file '/Users/brentley.jones/Developer/rules_xcodeproj/bazel-output-base/external/apple_support~~apple_cc_configure_extension~local_config_apple_cc/cc_toolchain_config.bzl' (expected 100570, got 95733 bytes)
```
or
```
ERROR: /Users/brentley.jones/Developer/rules_xcodeproj/bazel-output-base/external/apple_support~~apple_cc_configure_extension~local_config_apple_cc/cc_toolchain_config.bzl:2667:23: syntax error at 'newline': …
```
=> Copy files into `local_config_apple_cc` instead of symlinking

crosstool/cc_toolchain_config.bzl
The only thing stopping us from supporting the command line tools was
that we always tried to send the Xcode derived environment variables to
every action. For the command line tools there are reasonable
replacements that should always be safe to hardcode. The only thing
weird about this setup is that the target uses the default in bazel
which is currently 10.11. It respects --macos_minimum_os, so that's
probably fine.
In this setup the SDK version is not part of the cache key, users could
pass something in the --action_env to solve this if they wanted. That
seems hard enough to manage just from the CLT installation side so it
probably just doesn't matter for this use case.
=> Add support for CLT only

crosstool/osx_cc_configure.bzl, crosstool/osx_cc_wrapper.sh.tpl, test/rpaths/BUILD, test/rpaths/bar.cc, test/rpaths/baz.cc, test/rpaths/foo.cc, test/rpaths/test-portable.sh, test/rpaths/test.cc
This is no longer used in bazel so we should just own it. This copies
over the relevant shell test too.
=> Copy osx_cc_wrapper.sh.tpl from bazel

test/rpaths/BUILD
Fixes:
```sh
--
  | <pre><code><a href="https://github.com/bazelbuild/apple_support/blob/582600d6c9882eccfaf95577498db72b19aa33d6/test/rpaths/BUILD#L3">test/rpaths/BUILD:3:1</a>: <a href="https://github.com/bazelbuild/buildtools/blob/main/WARNINGS.md#native-cc">native-cc</a>: Function "cc_library" is not global anymore and needs to be loaded from "@rules_cc//cc:defs.bzl".
  | <a href="https://github.com/bazelbuild/apple_support/blob/582600d6c9882eccfaf95577498db72b19aa33d6/test/rpaths/BUILD#L8">test/rpaths/BUILD:8:1</a>: <a href="https://github.com/bazelbuild/buildtools/blob/main/WARNINGS.md#native-cc">native-cc</a>: Function "cc_binary" is not global anymore and needs to be loaded from "@rules_cc//cc:defs.bzl".
  | <a href="https://github.com/bazelbuild/apple_support/blob/582600d6c9882ecc …
```
=> Fix buildifier errors

xcode/providers.bzl, xcode/xcode_sdk_variant.bzl
This is a very simple data-propagating rule (it contains no actions) that will be used to encode the SDK details of each version of Xcode into the build graph.
PiperOrigin-RevId: 714123579
=> Add the `xcode_sdk_variant` rule.

xcode/providers.bzl, xcode/xcode_sdk_variant.bzl
It was only meant to hold the user-friendly version, not the full build version (the latter is already in the `build_version` attribute).
PiperOrigin-RevId: 715041518
=> Correct the documentation for the `xcode_sdk_variant.version` attribute.

.bazelci/presubmit.yml, .pre-commit-config.yaml
The rules_cc rules don't work with bazel 6.x
=> Downgrade buildifier

crosstool/BUILD.tpl, crosstool/cc_toolchain_config.bzl, crosstool/libtool.sh.tpl, crosstool/osx_cc_configure.bzl, crosstool/osx_cc_wrapper.sh.tpl, crosstool/universal_exec_tool.bzl
This causes the tools to be built on the execution platform, which might not be the same as the host platform. This is needed to support cross-platform RBE builds.
=> Use build rules for some toolchain tools

crosstool/cc_toolchain_config.bzl
Matches rules_cc: https://github.com/bazelbuild/rules_cc/blob/6a2520bed08bbe47a8afcf4c43d51c2533d79ed8/cc/private/toolchain/unix_cc_toolchain_config.bzl#L1648.
=> Enable the `archive_param_file` feature by default

crosstool/setup.bzl
Because we use the toolchain API, this should be a no-op on non-macOS builds. This allows for cross-platform RBE.
=> Always create toolchain

crosstool/cc_toolchain_config.bzl
This is something I could use in my codebase. I would like have a way to propagate the `-w` flag to all clang-using targets, and specifically, selectively disable it in my REPO.bazel and individual targets. This would allow me to globally suppress warnings for external repositories, without enabling it in my own code, and without needing to juggle the state of the flag setting (`-w` and other diagnostic flags are mutually exclusive afaik). This is the same as how we organize the `treat_warnings_as_errors` feature today. 
Companion change in rules_swift is bazelbuild/rules_swift#1489
=> add `suppress_warnings` feature

crosstool/cc_toolchain_config.bzl
This feature is used in bazel to disable anything related to .d files.
This is off by default but must be here to be enabled.
=> Add no_dotd_file well known feature

crosstool/cc_toolchain_config.bzl
I think this is some legacy workaround
=> Remove unnecessary executable from toolchain

crosstool/cc_toolchain_config.bzl, test/linking_tests.bzl
Sidestep https://github.com/bazelbuild/apple_support/issues/371 until
it's fixed in Xcode. Users who still want this vs can pass
`--linkopt=-Os`
This reverts commit 27df79d278aac09e3d973b98af2553f0a569cba3.
=> Revert "Enable link time -Os in opt builds (#348)"

crosstool/universal_exec_tool.bzl
The core problem was fixed in https://reviews.llvm.org/D111269 and these
workarounds are no longer necessary.
=> Remove no_uuid and codesigning workarounds when building wrapped_clang.

crosstool/libtool.sh.tpl
=> Fix when `libtool` is called from a location other than Bazel’s execution root

test/BUILD, test/cc_toolchain_forwarder.bzl, test/linking_support.bzl, test/starlark_apple_binary.bzl, test/starlark_apple_static_library.bzl
Changes based on https://github.com/bazelbuild/rules_apple/commit/0410c024c1eac29f8cfbe4f7c78bef54c92d0422
Fixes past https://github.com/bazelbuild/bazel/commit/4f40b7fb7b0521b56767dcf147d4d13e21f3b692
=> Update for get_cpu upstream removal

crosstool/BUILD, test/starlark_apple_binary.bzl, test/starlark_apple_static_library.bzl
This way we can delete the one in bazel itself. This is only used in bazel 6.x and in tests
=> Use xcrunwrapper from this repo

test/binary_tests.bzl, test/shell/BUILD, test/shell/verify_object_hashes.sh, test/test_data/BUILD, test/test_data/duplicate.cc, test/test_data/nested/duplicate.cc
This makes sure we don't break our libtool behavior to hash files if
there are duplicate basenames
=> Add test for archive file hashes

.bazelci/presubmit.yml
This does nothing except when 2 versions are available on CI but
produces a warning in buildkite when the version is invalid
=> Remove xcode_version from CI config

test/shell/verify_object_hashes.sh, test/test_data/BUILD
Interestingly today even non-duplicate names are symlinked and hashed.
I think we should probably change this just for clarities sake but at
least this encodes today's behavior
=> Add another case for duplicate object basenames

crosstool/BUILD, crosstool/BUILD.tpl, crosstool/osx_cc_configure.bzl
Now that we're building the tools used in the toolchain as normal rules,
there's really no need for them to be part of the toolchain setup. This
is more understandable in general since it removes a layer of
indirection.
=> Move toolchain tool setup out of repo rule

.bazelci/presubmit.yml, MODULE.bazel, lib/repositories.bzl, test/available_xcodes_test.bzl, test/xcode_config_test.bzl, test/xcode_version_test.bzl, xcode/BUILD, xcode/available_xcodes.bzl, xcode/private/BUILD, xcode/private/providers.bzl, xcode/xcode_config.bzl, xcode/xcode_config_alias.bzl, xcode/xcode_version.bzl
PiperOrigin-RevId: 631018102
(cherry picked from commit f1bbadc4aef7b62450b5db96b05c3da6e337900c)
=> Fork the Xcode rules from Bazel built-in Starlark into `apple_support`

crosstool/BUILD, crosstool/osx_cc_wrapper.sh.tpl
Otherwise path mapping does not work with these files since the path to
wrapped clang contained the transition hash. Now we fetch the relative
path to wrapped_clang dynamically.
=> Remove relative path to wrapped_clang from osx_cc_wrapper.sh

.bazelrc
This was for 6.x compat which we dropped
=> Remove old crosstool flags

.bazelci/presubmit.yml, crosstool/cc_toolchain_config.bzl, crosstool/wrapped_clang.cc, test/binary_tests.bzl
This linker bug was fixed in Xcode 16.3. It would be a bit of a pain to
support both so this just reverts the fix and users on the older
versions should stay on older apple_supports until they upgrade Xcode.
Fixes https://github.com/bazelbuild/apple_support/issues/401
Fixes https://github.com/bazelbuild/apple_support/issues/404
This reverts commit 8ee7a2df6ef9a169395866f614869510b4d586e8.
=> Revert "Fix oso_prefix paths (#347)"

crosstool/libtool.cc
In general one shouldn't call waitpid until the child closed its end of the pipe. This works fine with libtool invocations that do not produce more than `_PC_PIPE_BUF` bytes of output but deadlocks when the pipe fills up.
=> Consume the pipes before waiting for pid

crosstool/setup.bzl, crosstool/setup_internal.bzl, lib/repositories.bzl
This removes an unnecessary lockfile entry.
The module extension is kept in place so that `use_extension` calls don't need to be updated. The repo rules are moved into a separate file so that WORKSPACE setups don't fail on a cyclic load of `bazel_features`. The newly exposed repo rules are protected by load visibility.
=> Mark module extension as reproducible

.bazelci/presubmit.yml, crosstool/cc_toolchain_config.bzl, crosstool/wrapped_clang.cc, test/linking_tests.bzl
Add support for generating a .dSYM file if this is requested using `--apple_generate_dsym`. This change contains the following patches:
* Add `DSYM_HINT` flags to be picked up by `wrapped_clang` to generate .dSYM bundles on request.
* In `wrapped_clang.cc` make sure the linked binary is stripped after generating the .dSYM bundle first to make the .dSYM bundle contain useful information.
Adopts [changes](https://github.com/bazelbuild/bazel/pull/25881) in bazel to support .dSYM files (as part of fixing https://github.com/bazelbuild/bazel/issues/16893).
=> cc_binary: support .dSYM generation

crosstool/cc_toolchain_config.bzl
This is needed for LTO builds, this is the path to which linker writes one big object file after performing link time optimisations, and then this object file would be used during final linking to create the App binary, without this file binary would contain invalid debug symbols, more info - https://github.com/bazelbuild/rules_swift/issues/1529 . 
To enable this you need to pass `bazel build --features=full_lto` or `bazel build --features=thin_lto`, along with `rules_swift` LTO features. 
Closes - https://github.com/bazelbuild/rules_swift/issues/1529
=> Pass -object_path_lto <path> linker flag for LTO builds

crosstool/cc_toolchain_config.bzl, test/compiling_tests.bzl, test/test_data/BUILD
Default flags should come before flags passed with `--copt` or `copts = []`
Broken by 7009b77c98a67d3fea081c9db4dbcee8effc3b7e fixes https://github.com/bazelbuild/apple_support/issues/422
=> Fix cxx_flags order

crosstool/cc_toolchain_config.bzl
Fixes https://github.com/bazelbuild/apple_support/issues/423
We should re-apply with the actual configs for full_lto and thin_lto, we
should be able to write a test to verify it works too.
This reverts commit 61b44d12df0834ae26d6e089271e14c6c9a239c8.
=> Revert "Pass -object_path_lto <path> linker flag for LTO builds (#420)"
